### ISSUE TITLE
Last CoreDNS release unable to start

### ISSUE THREAD

**Issue by dramirez-qb** [loft-sh/vcluster#1141]
### What happened?

the provisioning of a new vcluster with the current config for CoreDNS fails to start due the [new release of CoreDNS](https://github.com/coredns/coredns/releases)

```shell
exec /coredns: operation not permitted
```

### What did you expect to happen?

a brand new vcluster

### How can we reproduce it (as minimally and precisely as possible)?

```shell
vcluster create test # fixed by using the previous version (next details)
```

### Anything else we need to know?

<details>

fixed by addind to the file installation (`values.yaml`) the following

```yaml
coredns:
  image: coredns/coredns:1.10.1
```

```shell
 vcluster create test -f values.yaml
```

</details>

### Host cluster Kubernetes version

<details>

```console
$ kubectl version
WARNING: This version information is deprecated and will be replaced with the output from kubectl version --short.  Use --output=yaml|json to get the full version.
Client Version: version.Info{Major:"1", Minor:"27", GitVersion:"v1.27.4", GitCommit:"fa3d7990104d7c1f16943a67f11b154b71f6a132", GitTreeState:"clean", BuildDate:"2023-07-19T12:20:54Z", GoVersion:"go1.20.6", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v5.0.1
Server Version: version.Info{Major:"1", Minor:"27", GitVersion:"v1.27.4+k3s1", GitCommit:"36645e7311e9bdbbf2adb79ecd8bd68556bc86f6", GitTreeState:"clean", BuildDate:"2023-07-28T09:46:04Z", GoVersion:"go1.20.6", Compiler:"gc", Platform:"linux/amd64"}
```

</details>

### Host cluster Kubernetes distribution

<details>

```
k3s
```

</details>

### vlcuster version

<details>

```console
$ vcluster --version
vcluster version 0.15.2
```

</details>

### Vcluster Kubernetes distribution(k3s(default)), k8s, k0s)

<details>

```
k3s
```

</details>

### OS and Arch

<details>

```
OS:  Linux
Arch: amd64
```
</details>

**Comment by lorenzo-w** [comment]
Facing the same issue, pinned `coredns.image.tag` to 1.10.1 as a workaround.

**Comment by waveywaves** [comment]
Hi team, I would like to contribute a fix for this issue. I understand that the image tag needs to be updated, would appreciate the help with understanding the same.

**Comment by barrydobson** [comment]
I'm also seeing this issue. I believe it's down to the fact that the 1.11 version of the CoreDNS docker container is set to run as a non root user.

**Comment by FabianKramm** [comment]
@dramirez-qb thanks a lot for the issue! We will fix this ASAP

**Comment by dramirez-qb** [comment]
Thank for the quick feedback

Fixed by #1142

**Comment by FabianKramm** [comment]
We will release a new vcluster version today that will include this fix, thanks again for providing the detailed information!

**Comment by FabianKramm** [comment]
Should be fixed with v0.15.4

**Comment by jkremser** [comment]
Now with version `0.15.5` we have this issue with coredns pod not starting:

```
kube-system   coredns-6dbc949d9c-lx47w                                         0/1     CrashLoopBackOff   114 (5m2s ago)   9h
```
```
kubectl logs -f coredns-6dbc949d9c-lx47w -n kube-system
[WARNING] No files matching import glob pattern: /etc/coredns/custom/*.server
plugin/errors: /etc/coredns/Corefile:3 - Syntax error: Unexpected token 'stacktrace', expecting 'consolidate'
```
When I removed the “stacktrace” plugin from the coredns configmap, it started fine.

The image for `coredns` was set to `coredns/coredns:1.8.7`
The image for `vcluster` was `k3s:v1.24.14-k3s1`

Downgrading `vcluster` to `0.15.2` works as a workaround.

it's weird, because according the [tests](https://github.com/coredns/coredns/blob/master/plugin/errors/setup_test.go) the:

```
errors {
   stacktrace
}
```
chunk of config should be fine, but we got that weird error msg during coredns startup, that it's not. Maybe some version mismatch.. the `coredns@1.8.7` looks pretty old (~2years). Not sure how such old version got installed. But to my knowledge, we don't tune the coredns version anyhow in our setup.

**Comment by jkremser** [comment]
ah, it must be coming from that `rancher/k3s:v1.24.14-k3s1`, let me try something here:

```
k3d cluster create --image=rancher/k3s:v1.24.14-k3s1 --no-lb --k3s-arg "--disable=traefik,servicelb,metrics-server,local-storage@server:*"
...
k describe pod -lk8s-app=kube-dns -n kube-system | grep Image:                                                                                                                                                  ○ k3d-k3s-default
    Image:         rancher/mirrored-coredns-coredns:1.10.1
```

`¯\_(ツ)_/¯`

when trying `rancher/k3s:v1.24.16-k3s1` it installs the same (`1.10.1`) version. Still not sure where that `1.8.7` is coming from in our setup and why upgrading `vcluster` binary causes this issue.

**Comment by ishankhare07** [comment]
hey @jkremser , I just verified the 0.15.5 vcluster release and by default its supposed to use the `coredns/coredns:1.10.1`
with the following corefile configuration
```
  Corefile: |-
    .:1053 {
        errors {
            stacktrace
        }
        health
        ready
        rewrite name regex .*\.nodes\.vcluster\.com kubernetes.default.svc.cluster.local
        kubernetes cluster.local in-addr.arpa ip6.arpa {
            pods insecure
            fallthrough in-addr.arpa ip6.arpa
        }
        hosts /etc/NodeHosts {
            ttl 60
            reload 15s
            fallthrough
        }
        prometheus :9153
        forward . /etc/resolv.conf
        cache 30
        loop
        loadbalance
    }

    import /etc/coredns/custom/*.server

```

This is from a working newly created `0.15.5` vcluster. You need to check if you're overriding the default vcluster values somewhere while creating this
