### ISSUE TITLE
Upgraded to 0.22 from 0.20 , getting storageClass name not found issue

### ISSUE THREAD

**Issue by surabhinir** [loft-sh/vcluster#2384]
### What happened?

We upgraded from  0.20 t0 0.22. After upgrading PVC are not coming up.
Warning  VolumeMismatch  7s (x22 over 5m13s)  persistentvolume-controller  Cannot bind to requested volume "vcluster-search-master-pv-auth-x-test1-orntd-x-vclus-b839fd130d": storageClassName does not match

in PV  storage class name is coming as : azureblob-fuse-premium

in PVC : vcluster-azureblob-fuse-premium-x-test1-orntd-x-vclu-bde7a601ce

### What did you expect to happen?

Storage class mismatch should not be there

### How can we reproduce it (as minimally and precisely as possible)?

upgrade from 0.20 to 0.22 with   custom pv and pvc with storage class as azureblob-fuse-premium

### Host cluster Kubernetes version

v1.30.5

### vcluster version

    vcluster-commerce-dev-eastus2-001 | commerceaksdev01 | test1-orntd | Running | 0.22.0  |           | 2025-01-07 12:59:27 +0000 UTC | 19h33m25s | OSS

### VCluster Config

controlPlane:
  proxy:
    extraSANs:
    - '{{ .Release.Name }}.{{ .Release.Namespace }}'
  ingress:
    spec:
      ingressClassName: nginx
      tls: []
    annotations:
      nginx.ingress.kubernetes.io/backend-protocol: HTTPS
      nginx.ingress.kubernetes.io/ssl-passthrough: "false"
      nginx.ingress.kubernetes.io/ssl-redirect: "true"
#  statefulSet:
#    scheduling:
#      podManagementPolicy: OrderedReady
  statefulSet:
    persistence:
      volumeClaim:
        storageClass: standard-disk-zrs
integrations:
  metricsServer:
    enabled: true
networking:
  replicateServices:
    fromHost:
    - from: test1-orntd/vcluster-commerce-dev-eastus2-001
      to: test1-orntd/vcluster-commerce-dev-eastus2-001
    - from: test2-orntd/vcluster-commerce-dev-eastus2-002
      to: test2-orntd/vcluster-commerce-dev-eastus2-002
    - from: test4-orntd/vcluster-commerce-dev-eastus2-004
      to: test4-orntd/vcluster-commerce-dev-eastus2-004
    - from: development/vcluster-commerce-dev-eastus2-003
      to: development/vcluster-commerce-dev-eastus2-003
    - from: test3-orntd/vcluster-database-dev-eastus2-001
      to: test3-orntd/vcluster-database-dev-eastus2-001
sync:
  fromHost:
    ingressClasses:
      enabled: true
    storageClasses:
      enabled: true
  toHost:
    ingresses:
      enabled: true
    persistentVolumes:
      enabled: true
rbac:
  clusterRole:
    enabled: false

**Comment by JayShane** [comment]
Can you provide the complete vcluster configuration yaml file

**Comment by surabhinir** [comment]
@JayShane : on top of OOB  provided file , we have this customization at out end
[vcluster-values-0.22.1.zip](https://github.com/user-attachments/files/18371971/vcluster-values-0.22.1.zip)

**Comment by mfabbri** [comment]
Thank you for your time @JayShane: I just want to add that the same configuration is working fine with 0.20 version. We rolled back the vcluster today to 0.20 and the issue disappeared. But we would really like to upgrade to the latest version.

**Comment by FabianKramm** [comment]
@surabhinir @mfabbri good news, I found the issue and it should be fixed via #2402, we will backport that to v0.21 and v0.22 as well

**Comment by mfabbri** [comment]
Hi @FabianKramm great news! We will monitor the #2402 then; when do you think it could be available? Thank you

**Comment by surabhinir** [comment]
hi @FabianKramm ,   I upgraded to  0.22.3   and i see bug is still there. Also i see this issue is reopened.
Can you please update the status .

**Comment by mfabbri** [comment]
Hi @FabianKramm, the issue is still there; do you have updates about it? Thanks

**Comment by johannesfrey** [comment]
The fix was also backported and will be part of the next 0.25 and 0.24 releases. Feel free to reopen if there should still be problems.
